### ISSUE TITLE
Causal chain pickle file not found

### ISSUE THREAD

**Issue by bbalaji-ucsd** [mjedmonds/OpenLockLearner-AAAI20#2]
I tried the default command in the README, and ran into the error below. 
Command: `python openlockagents/OpenLockLearner/main/openlock_learner_open_lock.py `

```
Traceback (most recent call last):
  File "openlockagents/OpenLockLearner/main/openlock_learner_open_lock.py", line 263, in <module>
    main()
  File "openlockagents/OpenLockLearner/main/openlock_learner_open_lock.py", line 197, in main
    three_solution_schemas_structure_space_path,
  File "/Users/username/OpenLockLearner-AAAI20/openlockagents/OpenLockLearner/io/causal_structure_io.py", line 29, in load_causal_structures_from_file
    with open(causal_chain_structure_space_path, "rb") as causal_chain_space_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/username/Desktop/openlocklearner_causal_chain_space.pickle'
```

**Comment by mjedmonds** [comment]
This has been fixed in 4514e90 and these files will automatically be generated if they do not exist. You can control the path using [openlock_learner_config.json](openlockagents/OpenLockLearner/openlock_learner_config.json)
