### ISSUE TITLE
two_solution_schemas.pickle not found

### ISSUE THREAD

**Issue by jordan-schneider** [mjedmonds/OpenLockLearner-AAAI20#3]
I imagine this is much the same as #2 

```
(open-lock) user@computer:~/OpenLockLearner-AAAI20$ python openlockagents/OpenLockLearner/main/openlock_learner_open_lock.py 
PARAMETERS:
{ 'ablation_params': {'TOP_DOWN': False, 'BOTTOM_UP': False, 'PRUNING': False, 'TOP_DOWN_FIRST_TRIAL': False, 'INDEXED_DISTRIBUTIONS': False, 'ACTION_DISTRIBUTION': False},
  'chain_sample_size': 1000,
  'data_dir': '~/Desktop/Mass/OpenLockLearningResults/cc3-ce4_subjects',
  'deterministic': False,
  'effect_probabilities': { 'door': 1,
                            'l0': 1,
                            'l1': 1,
                            'l2': 1,
                            'l3': 1.0,
                            'others': 0.0},
  'epsilon': 0.99,
  'epsilon_active': False,
  'epsilon_decay': 0.99,
  'full_attempt_limit': False,
  'global_alpha_update': 1,
  'intervention_mode': 'action',
  'intervention_sample_size': 10,
  'lambda_multiplier': 1,
  'local_alpha_update': 1,
  'multiproc': False,
  'num_agent_runs': 40,
  'print_messages': False,
  'src_dir': '/tmp/openlocklearner/1519268884979954621/src/',
  'test_action_limit': 3,
  'test_attempt_limit': 30,
  'test_num_trials': 1,
  'test_scenario_name': 'CE4',
  'train_action_limit': 3,
  'train_attempt_limit': 30,
  'train_num_trials': 6,
  'train_scenario_name': 'CC3',
  'use_physics': False,
  'using_ids': False}
/home/user/anaconda3/envs/open-lock/lib/python3.7/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
Loaded causal chain space from /home/user/OpenLockLearner-AAAI20/openlocklearner_causal_chain_space.pickle
Traceback (most recent call last):
  File "openlockagents/OpenLockLearner/main/openlock_learner_open_lock.py", line 202, in <module>
    main()
  File "openlockagents/OpenLockLearner/main/openlock_learner_open_lock.py", line 135, in main
    three_solution_schemas_structure_space_path,
  File "/home/user/anaconda3/envs/open-lock/lib/python3.7/site-packages/OpenLockAgents-1.0-py3.7.egg/openlockagents/OpenLockLearner/io/causal_structure_io.py", line 33, in load_causal_structures_from_file
    two_solution_schemas_structure_space_path, "rb"
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/OpenLockLearner-AAAI20/two_solution_schemas.pickle'
```

**Comment by jordan-schneider** [comment]
This was resolved somehow by downgrading networkx from 2.5 to 2.3, after which the connected_component_subgraphs function was deprecated, and then re-running setup.py. You probably want to fix that in requrements.txt
